// <auto-generated />
using System;
using Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251130162423_editbookingtickets")]
    partial class editbookingtickets
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Data.Models.Class", b =>
                {
                    b.Property<long>("Class_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Class_ID"));

                    b.Property<string>("ClassNameAR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClassNameEN")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Class_ID");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("Data.Models.Coach", b =>
                {
                    b.Property<long>("Coach_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Coach_ID"));

                    b.Property<long>("ClassId")
                        .HasColumnType("bigint");

                    b.Property<string>("CoachType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSeatless")
                        .HasColumnType("bit");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("int");

                    b.HasKey("Coach_ID");

                    b.HasIndex("ClassId");

                    b.ToTable("Coaches");
                });

            modelBuilder.Entity("Data.Models.Seat", b =>
                {
                    b.Property<int>("SeatID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SeatID"));

                    b.Property<long>("CoachID")
                        .HasColumnType("bigint");

                    b.Property<int>("SeatNumber")
                        .HasColumnType("int");

                    b.HasKey("SeatID");

                    b.HasIndex("CoachID");

                    b.ToTable("Seats");
                });

            modelBuilder.Entity("Data.Models.Station", b =>
                {
                    b.Property<long>("StationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("StationID"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StationCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StationNameAR")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("StationNameEN")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("StationID");

                    b.HasIndex(new[] { "StationNameAR" }, "IX_Stations_StationNameAR");

                    b.HasIndex(new[] { "StationNameEN" }, "IX_Stations_StationNameEN");

                    b.ToTable("Stations");
                });

            modelBuilder.Entity("Data.Models.Tickets.Booking", b =>
                {
                    b.Property<Guid>("Booking_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ArrivalStopID")
                        .HasColumnType("int");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BookingStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DepartureStopID")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("TripID")
                        .HasColumnType("int");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Booking_ID");

                    b.HasIndex("ArrivalStopID");

                    b.HasIndex("DepartureStopID");

                    b.HasIndex("TripID");

                    b.HasIndex(new[] { "UserID", "TripID" }, "IX_Bookings_UserID_TripID");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("Data.Models.Tickets.Payment", b =>
                {
                    b.Property<Guid>("Payment_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<Guid>("BookingID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PaymobOrderID")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PaymobTransactionID")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Payment_ID");

                    b.HasIndex("BookingID");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Data.Models.Tickets.Ticket", b =>
                {
                    b.Property<Guid>("Ticket_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Booking_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("ClassID")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("SeatID")
                        .HasColumnType("int");

                    b.Property<string>("TicketReference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Ticket_ID");

                    b.HasIndex("Booking_ID");

                    b.HasIndex("ClassID");

                    b.HasIndex("SeatID")
                        .IsUnique();

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("Data.Models.Train", b =>
                {
                    b.Property<long>("TrainID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TrainID"));

                    b.Property<string>("TrainName")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("TrainID");

                    b.HasIndex("TrainName");

                    b.ToTable("Trains");
                });

            modelBuilder.Entity("Data.Models.TrainCoach", b =>
                {
                    b.Property<long>("TrainID")
                        .HasColumnType("bigint");

                    b.Property<long>("Coach_ID")
                        .HasColumnType("bigint");

                    b.Property<int>("AvailableSeats")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("TrainCoach_ID")
                        .HasColumnType("int");

                    b.HasKey("TrainID", "Coach_ID");

                    b.HasIndex("Coach_ID");

                    b.ToTable("TrainCoaches");
                });

            modelBuilder.Entity("Data.Models.Trips.Trip", b =>
                {
                    b.Property<int>("TripID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TripID"));

                    b.Property<long?>("ArrivalStationID")
                        .IsRequired()
                        .HasColumnType("bigint");

                    b.Property<long?>("DepartureStationID")
                        .IsRequired()
                        .HasColumnType("bigint");

                    b.Property<string>("TrainCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TrainID")
                        .HasColumnType("bigint");

                    b.HasKey("TripID");

                    b.HasIndex("ArrivalStationID");

                    b.HasIndex("TrainID");

                    b.HasIndex(new[] { "DepartureStationID", "ArrivalStationID" }, "IX_Trips_Departure_Arrival");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("Data.Models.Trips.TripSegmentPrice", b =>
                {
                    b.Property<int>("SegmentPriceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SegmentPriceID"));

                    b.Property<long>("ClassID")
                        .HasColumnType("bigint");

                    b.Property<int>("EndStopID")
                        .HasColumnType("int");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("StartStopID")
                        .HasColumnType("int");

                    b.Property<int>("TripID")
                        .HasColumnType("int");

                    b.HasKey("SegmentPriceID");

                    b.HasIndex("ClassID");

                    b.HasIndex("EndStopID");

                    b.HasIndex("StartStopID");

                    b.HasIndex(new[] { "TripID", "ClassID" }, "IX_TripSegmentPrices_TripID_ClassID");

                    b.ToTable("TripSegmentPrices");
                });

            modelBuilder.Entity("Data.Models.Trips.TripStop", b =>
                {
                    b.Property<int>("TripStopID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TripStopID"));

                    b.Property<TimeSpan?>("ArrivalTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("DepartureTime")
                        .HasColumnType("time");

                    b.Property<decimal?>("DistanceFromStartKM")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<long?>("StationID")
                        .HasColumnType("bigint");

                    b.Property<int>("StopSequence")
                        .HasColumnType("int");

                    b.Property<int>("TripID")
                        .HasColumnType("int");

                    b.HasKey("TripStopID");

                    b.HasIndex(new[] { "StationID" }, "IX_TripStops_StationID");

                    b.HasIndex(new[] { "TripID", "StationID" }, "IX_TripStops_TripID_StationID");

                    b.HasIndex(new[] { "TripID", "StopSequence" }, "IX_TripStops_TripID_StopSequence")
                        .IsUnique();

                    b.ToTable("TripStops");
                });

            modelBuilder.Entity("Data.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfBirth")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("IsActive")
                        .HasMaxLength(10)
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfilePicture")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Data.Models.Coach", b =>
                {
                    b.HasOne("Data.Models.Class", "Class")
                        .WithMany("Coaches")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");
                });

            modelBuilder.Entity("Data.Models.Seat", b =>
                {
                    b.HasOne("Data.Models.Coach", "Coach")
                        .WithMany("Seats")
                        .HasForeignKey("CoachID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coach");
                });

            modelBuilder.Entity("Data.Models.Tickets.Booking", b =>
                {
                    b.HasOne("Data.Models.Trips.TripStop", "ArrivalStop")
                        .WithMany()
                        .HasForeignKey("ArrivalStopID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Data.Models.Trips.TripStop", "DepartureStop")
                        .WithMany()
                        .HasForeignKey("DepartureStopID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Data.Models.Trips.Trip", "Trip")
                        .WithMany("Bookings")
                        .HasForeignKey("TripID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Models.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArrivalStop");

                    b.Navigation("DepartureStop");

                    b.Navigation("Trip");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Data.Models.Tickets.Payment", b =>
                {
                    b.HasOne("Data.Models.Tickets.Booking", "Booking")
                        .WithMany("Payments")
                        .HasForeignKey("BookingID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("Data.Models.Tickets.Ticket", b =>
                {
                    b.HasOne("Data.Models.Tickets.Booking", "Booking")
                        .WithMany("Tickets")
                        .HasForeignKey("Booking_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Models.Class", "Class")
                        .WithMany()
                        .HasForeignKey("ClassID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Data.Models.Seat", "Seat")
                        .WithOne()
                        .HasForeignKey("Data.Models.Tickets.Ticket", "SeatID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Class");

                    b.Navigation("Seat");
                });

            modelBuilder.Entity("Data.Models.TrainCoach", b =>
                {
                    b.HasOne("Data.Models.Coach", "Coach")
                        .WithMany("TrainCoaches")
                        .HasForeignKey("Coach_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Data.Models.Train", "Train")
                        .WithMany("TrainCoaches")
                        .HasForeignKey("TrainID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Coach");

                    b.Navigation("Train");
                });

            modelBuilder.Entity("Data.Models.Trips.Trip", b =>
                {
                    b.HasOne("Data.Models.Station", "Arrival_Station")
                        .WithMany("ArrivalTrips")
                        .HasForeignKey("ArrivalStationID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Data.Models.Station", "Departure_Station")
                        .WithMany("DepartureTrips")
                        .HasForeignKey("DepartureStationID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Data.Models.Train", "Train")
                        .WithMany("Trips")
                        .HasForeignKey("TrainID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Arrival_Station");

                    b.Navigation("Departure_Station");

                    b.Navigation("Train");
                });

            modelBuilder.Entity("Data.Models.Trips.TripSegmentPrice", b =>
                {
                    b.HasOne("Data.Models.Class", "Class")
                        .WithMany("SegmentPrices")
                        .HasForeignKey("ClassID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Models.Trips.TripStop", "EndStop")
                        .WithMany()
                        .HasForeignKey("EndStopID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Models.Trips.TripStop", "StartStop")
                        .WithMany()
                        .HasForeignKey("StartStopID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Models.Trips.Trip", "Trip")
                        .WithMany("SegmentPrices")
                        .HasForeignKey("TripID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("EndStop");

                    b.Navigation("StartStop");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("Data.Models.Trips.TripStop", b =>
                {
                    b.HasOne("Data.Models.Station", "Station")
                        .WithMany("Stops")
                        .HasForeignKey("StationID");

                    b.HasOne("Data.Models.Trips.Trip", "Trip")
                        .WithMany("Stops")
                        .HasForeignKey("TripID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Station");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Data.Models.Class", b =>
                {
                    b.Navigation("Coaches");

                    b.Navigation("SegmentPrices");
                });

            modelBuilder.Entity("Data.Models.Coach", b =>
                {
                    b.Navigation("Seats");

                    b.Navigation("TrainCoaches");
                });

            modelBuilder.Entity("Data.Models.Station", b =>
                {
                    b.Navigation("ArrivalTrips");

                    b.Navigation("DepartureTrips");

                    b.Navigation("Stops");
                });

            modelBuilder.Entity("Data.Models.Tickets.Booking", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Data.Models.Train", b =>
                {
                    b.Navigation("TrainCoaches");

                    b.Navigation("Trips");
                });

            modelBuilder.Entity("Data.Models.Trips.Trip", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("SegmentPrices");

                    b.Navigation("Stops");
                });

            modelBuilder.Entity("Data.Models.User", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
